#!/usr/bin/env node
// vim: ft=javascript

// node modules
var fs = require('fs');

// npm modules
var app = require('commander');
var _ = require('underscore');
var clc = require('cli-color');
var shell = require('shelljs');

// app modules
var util = require('minify-util');

app
	.version('0.3.2')
	.option('-o, --output [path]', 'specify an output path (optional)')
	.option('-g, --git-hash', 'prepends the abbreviated git commit hash to the output filename')
	.option('-c, --content-hash', 'prepends an abbreviated hash based on the minified output')
	.option('-a, --append [string]', 'append a custom string to the output filename [.min]', '.min')
	.option('-v, --verbose', 'write verbose output', false)
	.parse(process.argv);

// set dirname
app.__dirname = __dirname;

// show help if there aren't any input files specified
if (app.args.length === 0) app.help();

// check for command-line tools
_.each(['git', 'jpegtran', 'optipng'], function (prereq) {
	if ( shell.which(prereq) ) return;
	console.log('oops, please install ' + prereq);
	process.exit(1);
});

var supported = ['js', 'css', 'php', 'html', 'png', 'jpeg', 'jpg'];

_.each(app.args, function (file) {

	// first, make sure file exists
	// and that it's actually a file

	try {
		var stat = fs.statSync(file);
		if (! stat.isFile()) {
			console.log(clc.red('ERROR ') + '"' + file + '" is an invalid file');
			return;
		}
	} catch (er) {
		console.log(clc.red('ERROR ') + '"' + file + '" is an invalid file');
		return;
	}

	var extension = _.last(file.split('.'));

	// make sure filetype is supported
	if (! _.contains(supported, extension)) return;

	// skip files that contain '.min'
	if (file.search('.min') > 0) {
		console.log(clc.underline('Skipping ' + '"' + file + '"'));
		console.log('');
		return;
	}

	// create the output filename
	var output = util.output(file, app);

	// grab the appropriate minifier
	var minifier = require('minify-minifiers')[extension];

	if (app.verbose)
	{
		switch (extension) {
			case 'jpg':
			case 'jpeg':
			case 'png':
				var message = 'Compressing';
			default:
				var message = 'Minifying';
		}

		console.log(clc.underline(message + ' "' + file + '"'));
	}

	// hot sauce
	minifier(file, output, app);

	if (app.verbose)
	{
		var diff = fs.statSync(file).size - fs.statSync(output).size;
		console.log(clc.green('SAVED ') + output);
		console.log(clc.blue('INFO ') + 'file size reduced by ' + diff + 'B');
		console.log('');
	}
	else
	{
		console.log(file + ':' + output);
	}
});
